name: 'Run node tests'
description: 'Setup Node environment and run install, audit, test, and build commands'
branding:
  icon: 'package'
  color: 'green'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: 'lts/*'
  npm-version:
    description: 'npm version to use if different from the default'
    required: false
    default: ''
  working-directory:
    description: 'Directory to run the commands in'
    required: false
    default: '.'
  cache-dependency-path:
    description: 'Path to the dependency file to use for caching (relative to working-directory)'
    required: false
    default: 'package-lock.json'
  install-skip:
    description: 'Skip npm install'
    required: false
    default: 'false'
  skip-install:
    description: 'Skip npm install'
    required: false
    default: 'false'
  install-command:
    description: 'Command to run npm ci/install'
    required: false
    default: 'npm ci'
  audit-skip:
    description: 'Skip npm audit'
    required: false
    default: 'false'
  skip-audit:
    description: 'Skip npm audit'
    required: false
    default: 'false'
  audit-command:
    description: 'Command to run npm audit'
    required: false
    default: 'npm audit --audit-level=high --production'
  test-skip:
    description: 'Skip tests'
    required: false
    default: 'false'
  skip-test:
    description: 'Skip tests'
    required: false
    default: 'false'
  test-command:
    description: 'Command to run tests'
    required: false
    default: 'npm test'
  build-skip:
    description: 'Skip build'
    required: false
    default: 'false'
  skip-build:
    description: 'Skip build'
    required: false
    default: 'false'
  build-command:
    description: 'Command to run build'
    required: false
    default: 'npm run build'

runs:
  using: 'composite'
  steps:
    - name: Set environment variables
      run: |
        echo "SKIP_INSTALL=$([ "${{ inputs.install-skip }}" = "true" ] || [ "${{ inputs.skip-install }}" = "true" ] && echo "true" || echo "false")" >> $GITHUB_ENV
        echo "SKIP_AUDIT=$([ "${{ inputs.audit-skip }}" = "true" ] || [ "${{ inputs.skip-audit }}" = "true" ] && echo "true" || echo "false")" >> $GITHUB_ENV
        echo "SKIP_TEST=$([ "${{ inputs.test-skip }}" = "true" ] || [ "${{ inputs.skip-test }}" = "true" ] && echo "true" || echo "false")" >> $GITHUB_ENV
        echo "SKIP_BUILD=$([ "${{ inputs.build-skip }}" = "true" ] || [ "${{ inputs.skip-build }}" = "true" ] && echo "true" || echo "false")" >> $GITHUB_ENV
      shell: bash

    - name: Setup cache dependency path environment variables
      run: |
        if [ "${{ inputs.working-directory }}" != "." ]; then
          echo "CACHE_DEPENDENCY_PATH=${{ inputs.working-directory }}/${{ inputs.cache-dependency-path }}" >> $GITHUB_ENV
        else
          echo "CACHE_DEPENDENCY_PATH=${{ inputs.cache-dependency-path }}" >> $GITHUB_ENV
        fi
      shell: bash

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        cache-dependency-path: ${{ env.CACHE_DEPENDENCY_PATH }}

    - name: Install npm
      if: ${{ inputs.npm-version }}
      run: npm install -g npm@${{ inputs.npm-version }}
      shell: bash

    - name: Run npm audit
      if: ${{ env.SKIP_AUDIT != 'true' }}
      run: ${{ inputs.audit-command }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Install dependencies
      if: ${{ env.SKIP_INSTALL != 'true' }}
      run: ${{ inputs.install-command }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Run tests
      if: ${{ env.SKIP_TEST != 'true' }}
      run: ${{ inputs.test-command }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Run build
      if: ${{ env.SKIP_BUILD != 'true' }}
      run: ${{ inputs.build-command }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}